@startuml ADD NEW STATION

header ADD NEW STATION

|User|
start
:User clicks new station button;
:User fills in station details;
|Server|
:Validate station details;
:Store station details in database;
if (Is station added?) then (no)
  |User|
  :show error message;
  stop
else (yes)
  |User|
  :show success message;
endif
stop

@enduml